package:
  name: nanocdr-x
  version: "1.0.0"

source:
  path: .

build:
  number: 1
  script: $PYTHON -m pip install .  # Install package during build
  post-link: post-link.sh  # Install missing dependencies AFTER conda-build

requirements:
  build:
    - python=3.11
    - pip
  run:
    - python=3.11
    - pandas=1.5.1
    - pip

test:
  commands:
    - predict_cdrs --help
    - explain_hidden_states --help
    - explain_saliency --help

about:
  home: https://github.com/lescailab/nanocdr-x
  license: MIT
  summary: "Predict and explain CDR regions in nanobody sequences"
  doc_url: https://github.com/lescailab/nanocdr-x#readme