package:
  name: nanocdr-x
  version: "1.0.0"

source:
  path: .

build:
  number: 1
  script: $PYTHON -m pip install .  # Install package during build
  post-link: post-link.sh  # Install missing dependencies AFTER conda-build

requirements:
  build:
    - python=3.11
    - pip
  run:
    - python=3.11
    - pandas=1.5.1
    - pip

test:
  source_files:
    - predict_nanobody_cdrs/example_data/example_input.csv
  commands:
    - predict_cdrs -i predict_nanobody_cdrs/example_data/example_input.csv -o test_output_cdrs.csv
    - explain_hidden_states -i predict_nanobody_cdrs/example_data/example_input.csv -o test_hidden_states.csv
    - explain_saliency -i predict_nanobody_cdrs/example_data/example_input.csv -o test_saliency.csv
  requires:
    - bash
  commands_pre:
    - test -f predict_nanobody_cdrs/example_data/example_input.csv
  commands_post:
    - test -f test_output_cdrs.csv
    - test -f test_hidden_states.csv
    - test -f test_saliency.csv

about:
  home: https://github.com/lescailab/nanocdr-x
  license: MIT
  summary: "Predict and explain CDR regions in nanobody sequences"
  doc_url: https://github.com/lescailab/nanocdr-x#readme